import GoogleAnalytics from "@/analytics/googleAnalytics";
import Footer from "@/components/footer";
import IfLandscape from "@/components/ifLandscape";
import Navbar from "@/components/navbar";
import NoMouse from "@/components/nomouse";
import SetScreenSize from "@/components/setscreensize";
import { AudioProvider } from "@/contexts/audiocontext";
import { Analytics } from "@vercel/analytics/react";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "./PretendardVariable.woff2",
  weight: "45 920",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <SetScreenSize />
      <html lang="kr" className={pretendard.className}>
        <AudioProvider>
          <body style={{ backgroundColor: "#eee7d1" }}>
            <IfLandscape />
            <NoMouse />
            <Navbar />
            {children}
            <Footer />
            <GoogleAnalytics />
            <Analytics />
          </body>
        </AudioProvider>
      </html>
    </>
  );
}
