import './globals.css'
import Navbar from '../components/navbar'
import localFont from 'next/font/local'
import Footer from '@/components/footer'
import SetScreenSize from '@/components/setscreensize'
import { Analytics } from "@vercel/analytics/react"
import GoogleAnalytics from './googleAnalytics'
import NoMouse from '@/components/nomouse'
import IfLandscape from '@/components/ifLandscape'
import { AudioProvider } from '@/context/audiocontext'

const pretendard = localFont({
  src: './PretendardVariable.woff2',
  weight: '45 920',
	style: 'normal',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <SetScreenSize/>
      <html lang="kr" className={pretendard.className}>
        <AudioProvider>
          <body style={{backgroundColor:'#eee7d1'}}>
            <IfLandscape/>
            <NoMouse/>
            <Navbar/>
            {children}
            <Footer/>
            <GoogleAnalytics/>
            <Analytics/>
          </body>
        </AudioProvider>
      </html>
    </>
  )
}
